apiVersion: v1
kind: Secret
metadata:
  name: keda-kafka-secrets
type: Opaque
data:
  authMode: "c2FzbF9wbGFpbnRleHQ="
  username: "YWRtaW4="
  password: "YWRtaW4="
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-kafka-credential
  namespace: kafkaplaypen
spec:
  secretTargetRef:
  - parameter: authMode
    name: keda-kafka-secrets
    key: authMode
  - parameter: username
    name: keda-kafka-secrets
    key: username
  - parameter: password
    name: keda-kafka-secrets
    key: password
    # - parameter: ca
    #   name: keda-kafka-secrets
    #   key: ca
    # - parameter: cert
    #   name: keda-kafka-secrets
    #   key: cert
    # - parameter: key
    #   name: keda-kafka-secrets
    #   key: key

---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  namespace: kafkaplaypen
spec:
  scaleTargetRef:
    kind: Deployment #StatefulSet
    name: kafka-slow-consumer #consumer
  pollingInterval: 5 #Interval for polling
  cooldownPeriod: 10
  minReplicaCount: 1
  maxReplicaCount: 3
  fallback: # Fallback strategy when metrics are unavailable for the apps
    failureThreshold: 2 #when metrics are unavailable, match the desired state of replicas 
    replicas: 1 #Keep this desired state when metrics are unavailable
  advanced:
    restoreToOriginalReplicaCount: true
    horizontalPodAutoscalerConfig:
      behavior: # Optional. Use to modify HPA's scaling behavior
        scaleUp:
          policies:
          - type: Percent
            value: 30
            periodSeconds: 5
        scaleDown:
          policies:
          - type: Percent
            value: 10
            periodSeconds: 5
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka-local.kafkaplaypen.svc.cluster.local:9092
      consumerGroup: test-consumer-group # Make sure that this consumer group name is the same one as the one that is consuming topics
      topic: my-topic
      # Optional
      #lagThreshold: ""
    authenticationRef:
      name: keda-trigger-auth-kafka-credential
