apiVersion: v1
kind: Service
metadata:
  labels:
    app: consumer
  name: consumer
  namespace: kafkaplaypen
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp
    port: 8080
    protocol: TCP
  selector:
    app: consumer
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consumer
  namespace: kafkaplaypen
spec:
  selector:
    matchLabels:
      app: consumer # has to match .spec.template.metadata.labels
  serviceName: consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: consumer
        image: marigonsilva/consumer:latest
        ports:
        - containerPort: 8080
          name: consumer
        command:
        - sh
        - -c
        - "exec python3 -u ./consumer.py"
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
