- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      app: kafka-local
    labels:
      app.kubernetes.io/component: kafka
      app.kubernetes.io/instance: kafka-local
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kafka
      app: kafka-local
    name: kafka-local
    namespace: kafkaplaypen
  spec:
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: tcp-client
      port: 9092
      protocol: TCP
      targetPort: kafka-client
    selector:
      app.kubernetes.io/component: kafka
      app.kubernetes.io/instance: kafka-local
      app.kubernetes.io/name: kafka
      app: kafka-local
    sessionAffinity: None
    type: ClusterIP
---
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      app: kafka-local
    labels:
      app.kubernetes.io/component: kafka
      app.kubernetes.io/instance: kafka-local
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kafka
      app: kafka-local
    name: kafka-local-headless
    namespace: kafkaplaypen
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: tcp-client
      port: 9092
      protocol: TCP
      targetPort: kafka-client
    - name: tcp-internal
      port: 9093
      protocol: TCP
      targetPort: kafka-internal
    selector:
      app.kubernetes.io/component: kafka
      app.kubernetes.io/instance: kafka-local
      app.kubernetes.io/name: kafka
      app: kafka-local
    sessionAffinity: None
    type: ClusterIP
---
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      app: kafka-local-zookeeper
    labels:
      app.kubernetes.io/component: zookeeper
      app.kubernetes.io/instance: kafka-local
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: zookeeper
      app: kafka-local-zookeeper
    name: kafka-local-zookeeper
    namespace: kafkaplaypen
  spec:
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: tcp-client
      port: 2181
      protocol: TCP
      targetPort: client
    - name: tcp-follower
      port: 2888
      protocol: TCP
      targetPort: follower
    - name: tcp-election
      port: 3888
      protocol: TCP
      targetPort: election
    selector:
      app.kubernetes.io/component: zookeeper
      app.kubernetes.io/instance: kafka-local
      app.kubernetes.io/name: zookeeper
      app: kafka-local-zookeeper
    sessionAffinity: None
    type: ClusterIP
---
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      app: kafka-local-zookeeper
    labels:
      app.kubernetes.io/component: zookeeper
      app.kubernetes.io/instance: kafka-local
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: zookeeper
      app: kafka-local-zookeeper
    name: kafka-local-zookeeper-headless
    namespace: kafkaplaypen
  spec:
    clusterIP: None
    clusterIPs:
    - None
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: tcp-client
      port: 2181
      protocol: TCP
      targetPort: client
    - name: tcp-follower
      port: 2888
      protocol: TCP
      targetPort: follower
    - name: tcp-election
      port: 3888
      protocol: TCP
      targetPort: election
    publishNotReadyAddresses: true
    selector:
      app.kubernetes.io/component: zookeeper
      app.kubernetes.io/instance: kafka-local
      app.kubernetes.io/name: zookeeper
      app: kafka-local-zookeeper
    sessionAffinity: None
    type: ClusterIP
