apiVersion: v1
kind: Service
metadata:
  labels:
    app: producer
  name: producer
  namespace: kafkaplaypen
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp
    port: 8083
    protocol: TCP
  selector:
    app: producer
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: producer
  namespace: kafkaplaypen
spec:
  selector:
    matchLabels:
      app: producer # has to match .spec.template.metadata.labels
  serviceName: producer
  replicas: 30
  template:
    metadata:
      labels:
        app: producer # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: producer
        image: marigonsilva/producer:latest
        ports:
        - containerPort: 8083
          name: producer
        command:
        - sh
        - -c
        - "exec python3 -u ./producer.py"
